version: "3"

services:
  mc:
    container_name: hm-craft
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      VERSION: 1.8
      ONLINE_MODE: "FALSE"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - ./data:/data
